name: Run Script on Push

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Qt and build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qt5-qmake g++ make

    - name: build
      run: |
        qmake "TIC_TAC_TOE_FINAL - game.pro"
        make

    - name: test
      run: |
        qmake TIC_TAC_TOE_FINAL_test.pro
        make
        if [ -f ./test_components ]; then ./test_components; else echo "test_components not found"; fi
        if [ -f ./test_ai ]; then ./test_ai; else echo "test_ai not found"; fi

    - name: deploy
      run: echo "Deployment Done"
