name: C++ Qt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt and build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qt5-qmake g++ make

    - name: Build project
      run: |
        qmake "TIC_TAC_TOE_FINAL - game.pro"
        make

    - name: Build tests
      run: |
        qmake TIC_TAC_TOE_FINAL_test.pro
        make

    - name: Run test_components
      run: |
        if [ -f ./test_components ]; then ./test_components; else echo "test_components not found"; fi

    - name: Run test_ai
      run: |
        if [ -f ./test_ai ]; then ./test_ai; else echo "test_ai not found"; fi
