name: Run Script on Push

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Qt and build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qt5-qmake g++ make

    - name: Debug - List .pro files
      run: find . -name "*.pro"

    - name: List files and folders (root)
      run: ls -l

    - name: List all files recursively
      run: find . -type f

    - name: Build main project
      run: |
        # Adjust the path if your .pro file is in a subdirectory
        if [ -f TIC_TAC_TOE_FINAL.pro ]; then
          qmake TIC_TAC_TOE_FINAL.pro
          make
        else
          echo "TIC_TAC_TOE_FINAL.pro not found"
          exit 1
        fi

    - name: Build and run tests
      run: |
        if [ -f TIC_TAC_TOE_FINAL_test.pro ]; then
          qmake TIC_TAC_TOE_FINAL_test.pro
          make
          [ -f ./test_components ] && ./test_components || echo "test_components not found"
          [ -f ./test_ai ] && ./test_ai || echo "test_ai not found"
        else
          echo "TIC_TAC_TOE_FINAL_test.pro not found"
        fi

    - name: Deploy
      run: echo "Deployment Done"
